### PR TITLE
Feature/fix conversation activate deactivate

### PR DESCRIPTION
**Pull request by SteveBarnett**
@justinvdm, a review, please.

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@justinvdm Actually, I'm rethinking this. New commits coming soon.

**Comment by SteveBarnett** [comment]
@justinvdm Ok, ready for review. Actually. I think.

**Comment by hodgestar** [comment]
@steve Any chance you could add a screenshot of what the result looks like?

**Comment by SteveBarnett** [comment]
@hodgestar Sure! Thusly: 
screenshot 2015-04-14 09 49 44

**Comment by SteveBarnett** [comment]
Hrm. I think the toggles should say Activated and Deactivated, like the nav. Will fix now.

**Comment by SteveBarnett** [comment]
After some tinkering and discussion, @justinvdm and I decided that the earlier version was better, so I reverted commits to get back to that. It looks like this: 
screenshot 2015-04-14 11 05 58

**Comment by hodgestar** [comment]
Woot. I like this version more too.

The Archive buttons seem a bit lost off by themselves, but perhaps that is
something for a separate PR.

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
