### PR TITLE
harden sequential send worker against deleted conversations.

### PR DESCRIPTION
**Pull request by jerith**
This caused the scheduler to fail.

```
2014-01-19 02:00:46+0000 [HTTP11ClientProtocol,client] Trying to find conversation 'fd1b54e658644425841ac391a37c8050' by batch_id.
2014-01-19 02:00:46+0000 [HTTP11ClientProtocol,client] u'Cannot find batch for batch_id 1249b7548d464198b9b10cbb0c3b6415'
2014-01-19 02:00:46+0000 [HTTP11ClientProtocol,client] Unhandled error in Deferred:
2014-01-19 02:00:46+0000 [HTTP11ClientProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File "/var/praekelt/vumi-go/ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/var/praekelt/vumi-go/ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
          File "/var/praekelt/vumi-go/ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/var/praekelt/vumi-go/ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1155, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/var/praekelt/vumi-go/ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
            result = g.send(result)
          File "/var/praekelt/vumi-go/go/apps/sequential_send/vumi_app.py", line 125, in poll_conversations
            then, now, [c.key for c in conversations]))
        exceptions.AttributeError: 'NoneType' object has no attribute 'key'
```

### CODE REVIEW

**Comment by hodgestar** [comment]
Question: What causes these conversations to be expected to exist but not? Should we be cleaning the missing conversations out of some sort of redis list or something?

**Comment by jerith** [comment]
Stopping the conversation should clear it from the list. We probably deleted the conversation(s?) in question without sending a stop message or something.

**Comment by hodgestar** [comment]
Should we remove the bad conversation keys from the list if we find them?

**Comment by jerith** [comment]
We might be getting a temporary failure of some kind. I'd rather log them and clean up manually when we get Sentry alerts.

**Comment by hodgestar** [comment]
:+1:, but we'll need to figure out what is happening eventually.

**Comment by jerith** [comment]
We'll have a better idea of what's going on once this branch lands and Sentry tells us about the missing conversations. :-)

**Pull request merged**
