### PR TITLE
Updated and clean-up delivery status displaying.

### PR DESCRIPTION
**Pull request by hodgestar**
Updating and cleaning of the delivery status displaying to fix bugs and track changes present in https://github.com/praekelt/vumi/pull/256.

### CODE REVIEW

**Comment by hodgestar** [comment]
Outstanding TODOs:
- Update a few unrelated tests to handle new status fields.
- Decide whether we want to use the new delivery_report_\* fields in the charts and what titles to give them.

**Comment by jerith** [comment]
:+1:

**Comment by hodgestar** [comment]
Test have been updated -- the question about whether to use the new delivery_report_{delivered, pending, failed} fields in the chart somewhere is still open.

**Comment by smn** [comment]
Also  :+1: Perhaps we can have two charts? One for progress and one for DR statuses?

**Comment by hodgestar** [comment]
It's been decided to delay adding the extra delivery report fields to the charts until Ryan decides what is needed in them.

**Pull request merged**
