### PR TITLE
Add support for wechat  & mxit fields on the contact model.

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
Ready for review.

**Comment by smn** [comment]
Travis seems to be stuck.

**Comment by jerith** [comment]
Don't we need a new model version and migration for the new fields on `Contact`?

**Comment by smn** [comment]
no because they default to `null`.

**Comment by jerith** [comment]
:+1:, but we _really_ need to find a better way to handle address types.

**Comment by smn** [comment]
@jerith yeah, agreed, thanks.

**Pull request merged**
