### PR TITLE
Indiciate routers and conversations that are not running in the campaign routing screen.

### PR DESCRIPTION
**Pull request by hodgestar**
Currently there is nothing in the campaign routing screen to show which conversations and routers are running.

### CODE REVIEW

**Comment by hodgestar** [comment]
This bit Indrani and I quite hard this Sunday and we ended up feeling really silly for having a deactivated router that we didn't notice.

Not ready for full review (tests need updating for a start), but wouldn't mind comments on the approach.

**Comment by justinvdm** [comment]
+1 on the approach, looks good so far.

**Comment by hodgestar** [comment]
Ready for review if Travis is happy.

**Comment by hodgestar** [comment]
What it looks like:
selection_004
Ready for review.

**Comment by hodgestar** [comment]
... some bikeshedding ensues ...

What it looks like now:

selection_007

Ready for re-review.

**Comment by justinvdm** [comment]
:+1:

**Pull request closed without merging**
