### PR TITLE
Account change confirmation email not received

### PR DESCRIPTION
**Pull request by justinvdm**
On my account page: https://go.vumi.org/account/details/
I uncheck the box "Receive SMS to confirm start of campaign"
I then click 'save'
I get a notification saying the link has been sent to my email.
However I never receive the email with the confirmation

### CODE REVIEW

**Comment by justinvdm** [comment]
After a crazy amount of trial and error, I figured out that the confirmation email was actually being sent, but google was spam filtering it because of the spam-like title: "Confirm account detail changes". Changing the title to "Confirm Vumi Go account detail changes".

**Comment by justinvdm** [comment]
Hrm, so that too is being spam filtered out. Will try something else. Any ideas?

**Comment by justinvdm** [comment]
"Vumi Go account detail change confirmation" works if everyone is okay with that

**Comment by hodgestar** [comment]
:+1: and tx for improving the test while you were there.

**Pull request merged**
