### PR TITLE
Add routers to routing screen

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by jerith** [comment]
If the routing table contains links to routers, some links between conversations and channels are not displayed. I suspect this is a symptom of the routers not being displayed.

**Comment by justinvdm** [comment]
@hodgestar I'm seeing this error when I try save from the routing screen:

``` js
ar s = {
    id: null,
    result: null,
    error: {
        fault: "InvalidRoutingTable",
        faultCode: 400,
        faultString: "Source outbound-receiving endpoint {u'uuid': u'ROUTER:keyword:17caf9b49bf549a29cf623eb492cf669:OUTBOUND:default'} should link to an inbound-receiving endpoint but links to {u'uuid': u'TRANSPORT_TAG:longcode_tagpool_2:longcode-20003:default'}"
    }
};
```

From what I understand, `TRANSPORT_TAG:longcode_tagpool_2:longcode-20003:default` would be an inbound receiving endpoint, right? Any idea?

**Comment by jerith** [comment]
I may have gotten inbound and outbound router endpoints mixed up. I'll look at what it'll take to fix that -- should be fairly straightforward.

**Comment by jerith** [comment]
@justinvdm #558 fixes the bad routing table and router configs generated by the wizard.

**Comment by justinvdm** [comment]
The only  change necessary was in [the first commit](https://github.com/praekelt/vumi-go/commit/e155d36a67dcff2925c38bfab735db4d920032de).To avoid landing all the noisy revert commits, the commit was cherry-picked straight to the develop-frontend branch. Closing this issue.

**Pull request closed without merging**
