### PR TITLE
Improve guarding against HTTP errors in HTTP API pushes.

### PR DESCRIPTION
**Pull request by hodgestar**
Currently we have a long list of exceptions, which is fragile and a maintenance burden.

### CODE REVIEW

**Comment by hodgestar** [comment]
Errors we weren't handling before included:
- `ConnectionLost`
- `twisted.web.error.Error`

**Comment by hodgestar** [comment]
Ready for review.

**Comment by justinvdm** [comment]
:+1: probably worth waiting for travis

**Comment by jerith** [comment]
:+1:

**Pull request merged**
