### PR TITLE
Better message storing for RTD

### PR DESCRIPTION
**Pull request by jerith**
There are a few places where we aren't correctly storing outbound messages to transports.

### CODE REVIEW

**Comment by justinvdm** [comment]
Do we need a test for opt outs? Not sure how those fit in.

**Comment by justinvdm** [comment]
Looks good otherwise.

**Comment by jerith** [comment]
> Do we need a test for opt outs? Not sure how those fit in.

Those behave similarly to billing messages. Now that we're checking and storing messages in `.publish_outbound()` instead of various other places, the test isn't strictly necessary. I can write one if you'd prefer, though.

**Comment by justinvdm** [comment]
Looking at the current tests, I think we've covered that already, happy with it as is. :+1:

**Pull request merged**
