### PR TITLE
Unable to export vxpolls data for survey with lots of users

### PR DESCRIPTION
**Pull request by smn**
It takes too long to collect all the data and haproxy kills the web request. We should turn this into a celery task that sends an email (or redirects somewhere once the download is ready).

### CODE REVIEW

**Comment by smn** [comment]
Not quite ready for review yet, tests are missing. @badlard and @hodgestar this addresses the issue raised for the GHR project.

**Comment by hodgestar** [comment]
Yay! Tx.

**Comment by smn** [comment]
Making sure `SurveyTestCase.test_export_user_data` fails, leaving this for monday.

**Comment by smn** [comment]
Ok tests passing ready for review.
I was a bit surprised I had to use HTTP POST for the action, but I'm assuming the UI does that by default(?). Leaving that detail for the reviewer.

**Comment by hodgestar** [comment]
:+1:. Having to POST actions is expected (GET's shouldn't trigger actions).

**Comment by smn** [comment]
Right, this triggers an email. For some reason I was still reasoning about it being just a download, in which case a GET could make sense.

**Pull request merged**
