### PR TITLE
Add pip freeze to Travis builds to help with debugging

### PR DESCRIPTION
**Pull request by hodgestar**
I found this to be useful while debugging #868.

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review.

**Comment by jerith** [comment]
`pip list` gives more human-readable output, including where packages are installed from, so it might be slightly better than `pip freeze` here.

:+1: either way.

**Comment by hodgestar** [comment]
Updated to use `pip list`. Ready for re-review and re-building by Travis.

**Comment by jerith** [comment]
:+1:

**Pull request merged**
