### PR TITLE
Billing statement message costs don't include session costs

### PR DESCRIPTION
**Pull request by justinvdm**
At the moment we assume they do.

### CODE REVIEW

**Comment by justinvdm** [comment]
Depends on #1064, otherwise ready for review.

**Comment by hodgestar** [comment]
Looks good, although I'd like to quickly take a final look after #1064 lands.

One point which I think needs discussion is whether credits or cost should be considered fundamental in our statement generation. Unless the cost-per-credit changes (which is unlikely) the point is a bit moot, but current we treat costs as the basic unit (i.e. what we sum from the transactions) and then derive credits (by calculating) but the credits are really what we deduct when transactions happen, so perhaps it would be safer to sum those and then calculate the $ costs?

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
