### PR TITLE
Change go_manage_metrics command to disable metric collection as opposed to enable

### PR DESCRIPTION
**Pull request by justinvdm**
We will be needing this once we have dashboards in place.

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review.

**Comment by justinvdm** [comment]
Ah sorry, not actually ready for review.

**Comment by justinvdm** [comment]
Actually ready for review now.

**Comment by hodgestar** [comment]
:+1: on the parts that aren't mine.

**Comment by justinvdm** [comment]
:+1: on the new parts once Travis is happy.

**Comment by justinvdm** [comment]
:+1:

**Pull request closed without merging**
