### PR TITLE
Can't delete a contact from a group

### PR DESCRIPTION
**Pull request by justinvdm**
I took the following steps:
- I am on a group page: e.g. https://go.vumi.org/contacts/group/5844c59dd26045b2955ee284413e3f3e/
- I check the box next to a contact row
- I click the delete btn in the header
- I get an error screen (attached)

Note: I don't get this error when deleting a contact from the contacts screen (i.e. not from a group)

screen shot 2013-08-26 at 1 21 40 pm

screen shot 2013-08-26 at 1 19 36 pm

### CODE REVIEW

**Comment by justinvdm** [comment]
@badlard `Delete` isn't named properly, since we are removing contacts from the group. Changing this to `Remove contacts`. That ok?

On a related note, the action buttons for our 'tables'/'lists' in the UI need some improvement. A bunch of buttons with text will fill up the actions bar pretty quickly, and is a bit unsightly. I think the fact that we need to specify `With group:` in the action bar is one symptom of the bad design here. Maybe we should talk about this with the UX guys that will be onboard soon?

**Comment by justinvdm** [comment]
We still have a button for removing contacts from smart groups, although it doesn't really make sense. It is out of the scope of this ticket, but I've created #666 for it.

**Comment by justinvdm** [comment]
Ready for review

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
