### PR TITLE
Move UI things to the right places

### PR DESCRIPTION
**Pull request by jerith**
We have a whole lot of UI stuff (templates, views, forms, etc.) that live in the wrong places, mostly for historical reasons. We need to figure out where these things should live and put them there.

This will potentially break in-flight UI branches, so it would be a good idea to agree on a time to do it.

### CODE REVIEW

**Comment by jerith** [comment]
Probably easiest to review this a commit at a time rather than all at once.

**Comment by jerith** [comment]
I accidentally broke the Wikipedia app's views. We need to rewrite them to work with conversation definition stuff anyway, though.

**Comment by peterp** [comment]
This looks good to me. :+1:

**Comment by hodgestar** [comment]
Can we maybe rename all of the `test_new_views.py` to `test_views.py` (or something better if someone can think of something better)?

**Comment by jerith** [comment]
I thought there was something I was forgetting. I'll rename them shortly.

**Comment by hodgestar** [comment]
I think `conversation_screen` does slightly the wrong thing in the case where there is no conversation definition -- it doesn't do anything with `view_name`. I don't know if anything uses it like that.

**Comment by hodgestar** [comment]
I think `go/conversation/templates/conversation/conversation_base.html` might have lost links to messages, contacts and views (see https://github.com/praekelt/vumi-go/commit/24731bb1fd7a55ebb21206e068f61ba715ac5de9#L0L11). Those links probably need to be somewhere in the default view. Are they somewhere else now?

@peterp -- see above too. :)

**Comment by hodgestar** [comment]
Pretty difficult to give a change this big a thorough review but I think it's ready to land after the test renaming and the couple of questions I raised have been discussed.

**Comment by peterp** [comment]
@hodgestar I think we're still trying to figure out how to make the wizard work.

**Comment by hodgestar** [comment]
Understood, but maybe the links should stay there until we've made them
work?

**Comment by peterp** [comment]
Aaah, good point.

**Comment by jerith** [comment]
I took the links out of `conversation_base.html` because they're part of the wizard flow. They're still in `wizard_base.html`.

**Comment by jerith** [comment]
The `conversation_screen` hackery was there as a temporary measure. It's still (kind of) necessary for multi_surveys, but it's doing the wrong thing there. I'm not actually sure what the correct behaviour should be for viewing a broken conversation, but there's a FIXME comment and we can figure it out in a new branch.

**Comment by hodgestar** [comment]
Cool. Can we get tickets for wikipedia and multi-surveys and mention all
the relevant things in their descriptions?

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
