### PR TITLE
Ensure Riak clients are properly cleaned up

### PR DESCRIPTION
**Pull request by jerith**
This builds on praekelt/vumi#957.

### CODE REVIEW

**Comment by jerith** [comment]
Although Travis is configured to run the tests with manager closed assertions enabled, we don't yet have a vumi release with that functionality.

**Comment by hodgestar** [comment]
I'm wondering whether it would be cool to make the VumiApi a context manager so we can do `with get_vumi_api() as api: ...`?

**Comment by jerith** [comment]
I thought about that, but there are a lot of places (especially in the async stuff) where the creation and cleanup happen in different places.

**Comment by hodgestar** [comment]
I was thinking mostly for use in Django land.

**Comment by jerith** [comment]
Ready for another review.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
