### PR TITLE
Add a session length cost field to transactions

### PR DESCRIPTION
**Pull request by justinvdm**
We have a session length credits field but not a session length cost field. We need both for statements, and to make sure we the transaction table has all the information it could need for auditing purposes.

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review.

**Comment by justinvdm** [comment]
Realised we also probably want a session unit credits field on Transaction for completeness sake. Actually ready for review now.

**Comment by rudigiesler** [comment]
:+1: from me. depending on travis. I think you might want to merge in develop to get the latest travis file, to use riak 1.4

**Comment by hodgestar** [comment]
:+1:

**Comment by justinvdm** [comment]
@rudigiesler @hodgestar thanks for the +1. I realised it probably also makes sense to record the session length on the transaction, changing this PR to add that. Sorry to keep changing things after declaring it ready for review.

**Comment by justinvdm** [comment]
Actually ready for review this time, I hope.

**Comment by hodgestar** [comment]
:+1:

**Comment by justinvdm** [comment]
Session unit credit cost field removed from `Transaction`, ready for review.

**Comment by hodgestar** [comment]
More :+1:

**Pull request merged**
