### PR TITLE
Contact's extra fields aren't being displayed in the contact detail view.

### PR DESCRIPTION
**Pull request by justinvdm**
This led to a mild panic about running campaigns.

### CODE REVIEW

**Comment by hodgestar** [comment]
Could we get a test where we assert that the extra fields are included now?

**Comment by hodgestar** [comment]
Otherwise looks good. :)

**Comment by justinvdm** [comment]
Ready for re-review

**Comment by hodgestar** [comment]
Other than the tiny typo in the test name, :+1:.

**Pull request merged**
