### PR TITLE
Remove non-functional label of option for storing dialogue answers on contacts.

### PR DESCRIPTION
**Pull request by hodgestar**
Change `Display this screen in search results` to `Store this answer on contacts`.

### CODE REVIEW

**Comment by hodgestar** [comment]
Update: The code doesn't appear to honour this option any more so perhaps we should just remove it.

**Comment by SteveBarnett** [comment]
I think removing this is a great idea. We want to try and simplify the UI and (one part of this is to) [remove any bits left that are broken / missing](https://trello.com/c/pPXciPUe/15-1-review-ui-for-things-we-can-ditch-hide).

@badlard, @justinvdm, what do you think?

**Comment by badlard** [comment]
:+1:

**Comment by hodgestar** [comment]
Ready for review.

Update: Not ready -- need to fix two failing tests.

**Comment by hodgestar** [comment]
Ready for review.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
