### PR TITLE
Remove jsbox dependency on Django slugify()

### PR DESCRIPTION
**Pull request by jerith**

### CODE REVIEW

**Comment by hodgestar** [comment]
What were the changes from the Django version?

**Comment by jerith** [comment]
Adding a unicode check at the top, stripping out the `mark_safe` stuff that we don't need, and reformatting for PEP-8.

**Comment by hodgestar** [comment]
:+1:

**Comment by smn** [comment]
There's also https://pypi.python.org/pypi/slugify should people be interested in deferring this to a package instead.

**Comment by hodgestar** [comment]
:+1: again from me. Would also be fine with using the slugify package if people prefer.

**Comment by jerith** [comment]
I stuck with a copy of the one from Django because I didn't want to risk introducing subtle variations in slugification.

**Pull request merged**
