### PR TITLE
Remove routing entries when archiving router

### PR DESCRIPTION
**Pull request by jerith**

### CODE REVIEW

**Comment by jerith** [comment]
I didn't add a test for actually cleaning up the routing table, but I did test it manually. I'd really like to get #564 done before mucking about with routing tables any more.

**Comment by hodgestar** [comment]
Would really like this to have a test. Is writing a test for it particularly difficult?

**Comment by jerith** [comment]
It's about ten lines of ugly boilerplate that makes the test less readable. We already have a test around `archive_router()`, so we're pretty safe.

**Comment by hodgestar** [comment]
Not ideal but I'm :+1: on this. The method itself is tested -- it's just the results that aren't completely asserted on.

**Pull request merged**
