### PR TITLE
Use in-memory Riak backend instead of leveldb

### PR DESCRIPTION
**Pull request by jerith**

### CODE REVIEW

**Comment by jerith** [comment]
The build time is at the low end of our usual time range, but less disk access might reduce the variance when Travis is busy.

**Comment by hodgestar** [comment]
screenshot from 2015-02-12 11 02 38

**Comment by hodgestar** [comment]
My slight concern is that this makes our Travis builds more different to production.

**Comment by jerith** [comment]
> My slight concern is that this makes our Travis builds more different to production.

The set of features we use is identical between the `memory` and `eleveldb` backends. I'm specifically keeping vumi builds on `eleveldb` to catch any potential issues with our persistence layer there.

**Comment by calston** [comment]
:+1:

**Comment by hodgestar** [comment]
Happy for this to land and it's easy enough to switch back -- mostly just
wanted to register the concern.

**Pull request merged**
