### PR TITLE
Update requests usage to match later requests.

### PR DESCRIPTION
**Pull request by hodgestar**
```
File "/var/praekelt/vumi-go/ve/local/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)

  File "/var/praekelt/vumi-go/go/apps/dialogue/view_definition.py", line 40, in get
    model_data = r.json['result']['poll']

TypeError: 'instancemethod' object has no attribute '__getitem__'
```

### CODE REVIEW

**Comment by jerith** [comment]
This needs tests.

**Comment by jerith** [comment]
I'd be happier if we had a test that used requests so we can avoid this sort of problem in the future.

**Comment by justinvdm** [comment]
Looks good. I'm :+1: on this landing if we got tests to fail and then pass locally, don't think waiting for Travis is worth it if things are currently broken because of this.

**Comment by hodgestar** [comment]
@jerith I'm happy to open a ticket for converting this to request sessions based tests now that I know how to do that? Would like to land this though so we can fix production.

**Comment by jerith** [comment]
:+1: with a ticket for the tests that we work on today.

**Pull request merged**
