### PR TITLE
Display conversation type and attached channels in conversation dashboard

### PR DESCRIPTION
**Pull request by hodgestar**
- A lack of conversation type information makes it hard to find specific conversations (or to remember what sort of conversation is running).
- A lack of channels makes it easy to make mistakes like connecting something to the wrong channel or not connection a conversation up at all.

### CODE REVIEW

**Comment by hodgestar** [comment]
Currently looks like:

screenshot from 2014-11-06 12 03 12

**Comment by hodgestar** [comment]
@SteveBarnett would appreciate a review of this. Especially:
- Does it look like a good idea?
- Is it readable, understandable, not too ugly?

**Comment by SteveBarnett** [comment]
Couple of questions, but generally looks good :).

I'd like to usability test a variation or two of this (e.g. better as a separate column?) in the future. For now we should land this version. Is good?

I think it would be better to show `conversation_type` unslugified, since that's what it looks like elsewhere.

Will `empty` ever be reached? I thought you couldn't start a conversation without a channel?

For a later PR: filter by conversation_type. Shall I add that as a new issue?

**Comment by hodgestar** [comment]
Couple of answers:
- Happy to land this version if you think it's okay.
- Woot on usability testing some variations.
- I'll add a commit to unslugify the conversation type.
- One can create a conversation without channels using the + button on the routing screen or by disconnecting an existing conversation's channels.
- +1 on adding a filter by conversation type issue.

**Comment by hodgestar** [comment]
Aside: There is already backend support for filtering on conversations -- we just don't use it in the frontend anywhere!

Update: And for filtering on conversation status!

**Comment by hodgestar** [comment]
@SteveBarnett Regarding the conversation type -- it's slugified on the conversation view page. Does that mean we should keep it slugified here or should we start slowly changing it everywhere?

**Comment by SteveBarnett** [comment]
@hodgestar re your comments: cool.
Re conversation type: start slowly changing it everywhere, I think. The slugified version is for machines, not humans. But no huge rush getting them all changed.

**Comment by hodgestar** [comment]
@SteveBarnett Ready for re-review.

**Comment by hodgestar** [comment]
image

**Comment by SteveBarnett** [comment]
Bueno, :+1:

**Pull request closed without merging**
