### PR TITLE
added a test to confirm the local conversation store is protecting redis from being hit if the conv has been seen in 5min

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@hodgestar new test added. sorry for the super long PR name :/

**Comment by hodgestar** [comment]
:+1: once Travis is happy.

**Comment by KaitCrawford** [comment]
@hodgestar Travis is not happy :( `grunt test` failed with an error I don't understand:
`PhantomJS 1.9.8 (Linux 0.0.0) go.apps.dialogue.layout .DialogueStateLayout when the layout is double-clicked should create a new state at the mouse position FAILED`

**Comment by hodgestar** [comment]
Build failures were unrelated timeouts and rebuilding caused them to pass.

**Pull request merged**
