### PR TITLE
Add help for HTTP API access.

### PR DESCRIPTION
**Pull request by hodgestar**
Currently we have no help and confused people email us on a regular basis asking now to use the HTTP API.

### CODE REVIEW

**Comment by hodgestar** [comment]
@steve @justinvdm @jerith Ready for first review.

Bikeshedding encouraged.

**Comment by hodgestar** [comment]
http-api-help

Better formatting required.

**Comment by SteveBarnett** [comment]
Yay to having help stuff! :)
I have a bunch of things of various levels of niggle, though (of course :)).
- Consistent capitalisation of API, URL
- For ignore messages and ignore events, use the `.help-block` text as the label instead.
- Change the right, example, column class to `.col-md-7` to give it a bit more space.
- In the notes bit:
  - we should say `user` instead of `username`, since that's what it's called in the example.
  - say where the user can find their Vumi Go account key: at the bottom of [Account Details](http://localhost:8000/account/details/)
  - Replace "The hexadecimal value at the end of the string is the unique identifier for this conversation." with "The value at the end of the string is the unique identifier for this conversation. This conversation is {{current convo uuid}}."

Chatting with @justinvdm, he suggest moving the whole notes section to be contextual, and I agree. Like: "If your account key is `foo` and your conversation's id is `bar`, then your HTTP PUT request would look like this:"

**Comment by hodgestar** [comment]
http-api-help-2

**Comment by hodgestar** [comment]
http-api-help-2

**Comment by hodgestar** [comment]
@SteveBarnett @justinvdm I think I've addressed all of the comments except the one about changing `username` to `user`. A quirk of `curl` is that the argument to `--user` is both the username and the password so it seems less confusing to speak of `username` since it's only part of what is passed to `--user`.

**Comment by hodgestar** [comment]
Ready for re-review.

**Comment by SteveBarnett** [comment]
@hodgestar Looks great! :+1: from me.

**Comment by justinvdm** [comment]
Agreed :) :+1:

**Pull request merged**
