### PR TITLE
Add routing table helper function for computing the set of channels reachable from a given conversation.

### PR DESCRIPTION
**Pull request by hodgestar**
This is needed by the conversation show view (and will be pretty helpful for users :)

### CODE REVIEW

**Comment by hodgestar** [comment]
This is going to need a separate part that lives in `develop-frontend`.

**Comment by justinvdm** [comment]
Could we maybe add a bit more complex example and correspond tests for `transitive_targets()` and `transitive_sources()`? I've got a feeling the current example might be too basic to find out if we have those working properly.

**Comment by justinvdm** [comment]
:+1: once we have multi-step tests for `transitive_targets()` and `transitive_sources()`.

**Comment by hodgestar** [comment]
Ready for a re-review.

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
