### PR TITLE
Clean up conversation model

### PR DESCRIPTION
**Pull request by jerith**
The conversation model still contains obsolete fields that we shouldn't be using for anything anymore, particularly `delivery_tag_pool` and `delivery_tag`. We also need to swap out `batches` for a single `batch` foreign key.

### CODE REVIEW

**Comment by hodgestar** [comment]
:+1: on this but lets land it on Monday when everyone is back.

**Comment by jerith** [comment]
There's still some cleanup work I'd like to do (mostly removing `get_batches()` and `get_latest_batch_key()` which are used all over the place) but otherwise this branch is pretty much finished.

**Comment by hodgestar** [comment]
The fix-batches migration will currently display a lot of errors for new conversation models but it should probably just skip them (since they can't have anything other than 1 batch).

**Comment by hodgestar** [comment]
Cool. Reviewed everything so far.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
