### PR TITLE
Include a button for the new download modal in messages view

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review, but should only land once the download modal is hooked up to the message store.

**Comment by hodgestar** [comment]
Looks good but I think some tests need updating.

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by hodgestar** [comment]
:+1: (note for self & other readers: no to land until time-ranged message download backend is ready & hooked up)

**Comment by hodgestar** [comment]
I've merged this into #1345 because I'm going to have to work on the templates when I add a proper Django form for the time ranged downloads.

**Pull request closed without merging**
