### PR TITLE
Source dialogue endpoints allow multiple connections

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@SteveBarnett ready for review

**Comment by SteveBarnett** [comment]
:+1:, but what's up with Travis?

**Comment by justinvdm** [comment]
@SteveBarnett thanks, travis passed for python 2.6, and errored for python 2.7 with

```
Your test run exceeded 50 minutes. One possible solution is to split up your test run.
```

Restarting the build doesn't seem to be working, which I'm guessing is somehow related to the travis fixes/deployments that seem to be happening atm.

Since the changes in this PR is client-side js only, the fact that one of the builds passed is enough to validate that this PR doesn't break our builds. I'm going to land, hopefully the build for the merge into develop will run correctly on travis.

**Comment by SteveBarnett** [comment]
@justinvdm Cool cool cool.

**Comment by justinvdm** [comment]
@SteveBarnett ah, looks like the builds are finally regoing, will wait a bit.

**Pull request merged**
