### PR TITLE
VUMIGO-253 groups are timeout-prone, provide API

### PR DESCRIPTION
**Pull request by smn**
**Not ready for review yet**

The groups (specifically the smart groups) are very likely to create
timeouts in the webapp because:

1) they're unbounded by definition
2) we're trying to show the number of entries in a smart group in the Django UI
3) we're unable to page through the group members (same problem as the message display)

This PR is about creating an HTTP API in front of the group access where we can more efficiently query Riak & cache results (if necessary)

### CODE REVIEW

**Comment by smn** [comment]
This PR depends on https://github.com/praekelt/vumi/pull/446 for the ability to do `[dict(m) for m in models]`

**Comment by hodgestar** [comment]
We can hopefully use all of the stuff in `vumi.rpc` for this too now.

**Comment by hodgestar** [comment]
This can potentially be made part of `go.api.go_api` now if we want.

**Comment by hodgestar** [comment]
This is now part of the things to work on under #668.

**Comment by hodgestar** [comment]
Closing this in favour of praekelt/go-contacts-api#16 and praekelt/go-contacts-api#17.

**Pull request closed without merging**
