### PR TITLE
Container-based Travis builds

### PR DESCRIPTION
**Pull request by jerith**
They're faster to boot and support caching.

### CODE REVIEW

**Comment by JayH5** [comment]
lgtm, my only concern is that I vaguely remember someone somewhere (can't remember exactly) telling me to copy `utils/app.config` to `/etc/riak/app.config` to get Riak working for Vumi/Vumi Go on my local machine. With that file deleted it may make setup harder for people just wanting to try out Vumi.

**Comment by jerith** [comment]
Those configs still exist, but now they live in the `praekelt/riak-for-travis` repo and are better organised. :-)

**Comment by JayH5** [comment]
:+1:
The documentation around setting up Vumi on your local machine could do with some work...

**Comment by jerith** [comment]
Agreed, but that's out of scope for this PR.

**Pull request merged**
