### PR TITLE
Warn that conversation progress display may be inaccurate

### PR DESCRIPTION
**Pull request by jerith**
Due to praekelt/vumi#861, we may not be tracking events. We should note this in the UI.

### CODE REVIEW

**Comment by hodgestar** [comment]
:+1:

**Comment by SteveBarnett** [comment]
*puts on UX / content hat*

Could we change

> Updates may be temporarily disabled.

to

> Sorry, we're having trouble tracking message statistics at the moment, but we are working on it. That means the statistics might be out of date.

?

And for conversation/includes/charts could we add

> At the moment, these statistics are only generated for JavaScript apps.

?

---

@jerith Is this factually correct? ^^^
Want me to add commits to this branch with these changes?

Does this affect dashboard stats too?

**Comment by jerith** [comment]
If you're happy with the way the longer content looks, please make the change. (I didn't inspect the result at all, merely changed the templates.)

Is the "[...] only generated for JavaScript apps" relevant to this issue? I don't know if it's accurate, but even if it is that text will only be visible for jsbox conversations.

**Comment by jerith** [comment]
I'd rather not remove `charts.html` in this PR. It's not directly related to the issue and carries additional risk.

**Comment by SteveBarnett** [comment]
@hodgestar, still happy?

**Comment by jerith** [comment]
:+1: from me on the changes I didn't make, so we're good to go once Travis is happy.

**Comment by hodgestar** [comment]
Still :+1: from me too.

**Pull request merged**
