### PR TITLE
Billing API doesn't list costs without accounts

### PR DESCRIPTION
**Pull request by hodgestar**

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review.

**Comment by justinvdm** [comment]
Would it make sense to add a test for cases where we have a tag pool, but no account?

**Comment by justinvdm** [comment]
Otherwise, looks good.

**Comment by hodgestar** [comment]
@justinvdm It would. The `base_cost` defined at the start of the test is such a message cost entry (it's just not that evident from the diff).

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
