### PR TITLE
Update diamondash dependency

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review. As usual, there were other client side dependency updates in the process. We can stop this by pinning our dependencies to a specific version, but I'm not sure if we want to do that.

**Comment by hodgestar** [comment]
I think broader updates are fine in this case.

**Comment by hodgestar** [comment]
:+1:

**Comment by justinvdm** [comment]
Thanks for review :) Going to wait for Travis.

**Pull request merged**
