### PR TITLE
Don't monkeypatch socket module

### PR DESCRIPTION
**Pull request by jerith**
`moto` does this, and it breaks all other network access in obscure ways.

### CODE REVIEW

**Comment by jerith** [comment]
I still need direct tests for `S3Helper`, but everything else should be ready for an initial review.

**Comment by hodgestar** [comment]
Looks good.

**Comment by hodgestar** [comment]
Left one question about moto server clean up in the S3Helper tests, otherwise looks good.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
