### PR TITLE
pypy support

### PR DESCRIPTION
**Pull request by jerith**
This probably needs a little more thought before we decide if we want to land it, but we can update this branch periodically for Travis pypy builds or whatever.

### CODE REVIEW

**Comment by jerith** [comment]
There are some bulk send tests that will probably fail on pypy (due to errors logged in `Deferred.__del__()`) until praekelt/vumi#704 lands.

**Comment by rudigiesler** [comment]
:+1:

**Comment by jerith** [comment]
Bleh. The `PYPY_GC_MAX_PINNED` envvar was only added in 2.6.0, so it doesn't help here. :-(

**Comment by jerith** [comment]
Closed in favour of #1327.

**Pull request closed without merging**
