### PR TITLE
Tests for conversation object caching in helper metadata

### PR DESCRIPTION
**Pull request by jerith**
I've tested #803 manually and we need to get it out to mitigate a production issue. We still need to write automated tests for it.

### CODE REVIEW

**Comment by hodgestar** [comment]
We also need a test for `clear_object_cache` itself.

**Comment by hodgestar** [comment]
Looks good otherwise.

**Comment by jerith** [comment]
> We also need a test for `clear_object_cache` itself.

This is tested as part of the new test in this branch. I'll rename the test and add a docstring to reflect this.

**Comment by hodgestar** [comment]
We really need two tests here -- one for the new behaviour of
`get_conversation` and a separate one for the new `clear_object_cache`
method. The clear_object_cache test can be pretty simple.

**Comment by jerith** [comment]
> We really need two tests here

You're right, I was trying to do too much in the one test. Thanks.

**Comment by smn** [comment]
:+1: and I've restarted the travis build for this to be sure.

**Pull request merged**
